DRIVER_CAMERA_ID:
  "14442C1051EF97CD00"
FRONT_CAMERA_ID:
  "14442C10C1088FCD00"
REAR_CAMERA_ID:
  "14442C10910898CD00"

RED_ALERT_SIGNAL: 2
YELLOW_ALERT_SIGNAL: 1
NO_ALERT_SIGNAL: 0

YELLOW_ALERT_DISTANCE: 6000 # in mm
RED_ALERT_DISTANCE: 1000 # in mm

HEAD_DOSE_COUNT: 5
HEAD_TILT_COUNT: 5
YAWN_COUNT: 5
FATIGUE_TOTAL_COUNT: 8

# 234:416
MainImage_Height: 540
MainImage_Width: 960
DriverImage_Height: 420
DriverImage_Width: 540

MainWindowDimention: [1028, 846]

PRODUCTION: true